version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - tukang-ac-network

  # Backend (Golang - to be implemented separately)
  backend:
    image: golang:1.21-alpine
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:password@db:5432/tukang_ac?sslmode=disable
      - JWT_SECRET=your-jwt-secret-key
    depends_on:
      - db
    networks:
      - tukang-ac-network
    # volumes:
    #   - ./backend:/app
    # working_dir: /app
    # command: ["go", "run", "main.go"]

  # Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tukang_ac
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tukang-ac-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - tukang-ac-network

networks:
  tukang-ac-network:
    driver: bridge

volumes:
  postgres_data: